### ISSUE TITLE
"TypeError: Plugin is not a function" with Babel 6

### ISSUE THREAD

**Issue by lencioni** [stoeffel/babel-plugin-array-includes#1]
I just tried using this plugin with Babel 6 and I got the following error:

```
Module build failed: TypeError: Plugin is not a function
    at exports.default (/path/to/project/node_modules/babel-plugin-array-includes/lib/index.js:11:10)
    at Function.memoisePluginContainer (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:117:13)
    at Function.normalisePlugin (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:149:32)
    at /path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:183:30
    at Array.map (native)
    at Function.normalisePlugins (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:161:20)
    at OptionManager.mergeOptions (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:253:36)
    at OptionManager.addConfig (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:205:10)
    at OptionManager.findConfigs (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:346:16)
    at OptionManager.init (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:391:12)
```

I haven't tried using this plugin before, so I'm not sure if it is related to the new version or not.

**Comment by stoeffel** [comment]
Didn't try babel 6 yet. I guess they changed the plugin api. Will have to check the changlog.

**Comment by stoeffel** [comment]
...or maybe you would like to make a PR (I'm a little short on time right now). Would be awesome :+1:

**Comment by onemen** [comment]
This is working with babel 6.
this code is without the type check for array

```
"use strict";

exports.__esModule = true;

exports["default"] = function(babel) {
  const t = babel.types;

  return {
    visitor: {
      CallExpression(path) {
        let callee = path.node.callee;
        if (t.isMemberExpression(callee, {computed: false}) && 
            t.isIdentifier(callee.property, {name: "includes"})) {
          callee.property.name = "indexOf";
          path.replaceWith(
            t.binaryExpression(">=", path.node, t.numericLiteral(0))
          );
        }
      }
    }
  };
};

module.exports = exports["default"];
```

**Comment by stoeffel** [comment]
@onemen nice. would you like to make a PR?

**Comment by onemen** [comment]
I don't have the time to do it

**Comment by stoeffel** [comment]
> I don't have the time to do it

I will work on this as soon as I have time. Or maybe @lencioni got some time?

**Comment by ewendel** [comment]
I still experience this issue when using v1.1.1 of the plugin. The code I get in `node_modules/babel-plugin-array-includes/lib/index.js` is the old version, that fails on `new Plugin`.

Is it possible you've forgotten to re-publish to npm or similarly? @stoeffel

**Comment by stoeffel** [comment]
oups, sorry totally forgot to publish. v2.0.1 is released now. Could you check it out?

**Comment by ewendel** [comment]
Sure thing.

Is this version still without the type check, meaning that any function call by the name of `includes` will get transformed? I assume it wouldn't be difficult for someone plugin-savvy to add a check that the function call receiver is of type array.

**Comment by stoeffel** [comment]
> Is this version still without the type check, meaning that any function call by the name of includes will get transformed?

Yes, don't now how one can make the type check in babel 6 :-(

**Comment by stoeffel** [comment]
any hint or PR would be great.

**Comment by ewendel** [comment]
I was getting the old version, had to update my npm, now it's working fine - thanks!

If I happen to get some spare time I'll see what I can find out.

Without the type check this feature is rather useless imho - very dangerous to haphazardly replace all occurrances of the function name `includes`

**Comment by stoeffel** [comment]
> If I happen to get some spare time I'll see what I can find out.

awesome

> Without the type check this feature is rather useless imho - very dangerous to haphazardly replace all occurrances of the function name includes

agreed. I actually don't use this anymore :smile:
