### ISSUE TITLE
Gives a `peerDependency` warning when used in a preset

### ISSUE THREAD

**Issue by bebraw** [stoeffel/babel-plugin-array-includes#3]
I wonder if it's a good practice to use `peerDependency` here. Now you get the following when including the plugin to a Babel preset:

``` bash
npm WARN EPEERINVALID babel-plugin-array-includes@2.0.2 requires a peer of babel-core@>=6.3.0 but none was installed.
```

For example [babel-plugin-transform-decorators-legacy](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy) skips the `peerDependencies` declaration.

Maybe this would be a good place to use `optionalDependencies`. I'm not sure what's the best practice for Babel plugins. This is worth researching, though.

**Comment by stoeffel** [comment]
I will just remove it. I don't think this is necessary here.

**Comment by bebraw** [comment]
Ok, cool.

**Comment by stoeffel** [comment]
done (2.0.3)
btw. I don't use this plugin anymore and I'm looking for a maintainer. Are you using it? Interested in maintaining it?

**Comment by bebraw** [comment]
@stoeffel I just included it to the development version of [my book](http://survivejs.com/). The change was triggered by [MDN includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes).

Do you think it would make sense to push the plugin to the Babel project? Maybe they would be interested in keeping it up to date?

**Comment by stoeffel** [comment]
> @stoeffel I just included it to the development version of my book. The change was triggered by MDN includes.

Cool. Will check your book out.

> Do you think it would make sense to push the plugin to the Babel project?

Could be. I will think about it.
